options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/final', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'final',
        '--image', 'gcr.io/$PROJECT_ID/final',
        '--service-account', 'rarereleases2@rare-releases.iam.gserviceaccount.com',
        '--set-env-vars',
        'SPOTIFY_CLIENT_ID=ed8309594627474eb0c9365e265901c2,SPOTIFY_CLIENT_SECRET=52886e431d8c4a589c59f0594b020bf5,DISCOGS_TOKEN=dbnLETavMdFapPlyVIzZrGOsLmhqfRtsyglVpFMs',
        '--platform', 'managed',
        '--region', 'us-west2' 
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install virtualenv and create a virtual environment
        pip install virtualenv
        virtualenv -p python3 env
        
        # Activate the virtual environment and install dependencies
        source env/bin/activate
        pip install -r requirements.txt
        
        # Run the application
        python app.py

images:
  - 'gcr.io/$PROJECT_ID/final'